name: Upload Files  # Nome del workflow

on:
  push:  # Trigger: questo workflow parte quando fai un push
    branches:
      - main  # Sostituisci con il branch su cui lavorerai

jobs:
  upload:
    runs-on: ubuntu-latest  # Sistema operativo per eseguire il job

    steps:
      # Step 1: Clonare il repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Copiare i file dalla cartella output nel repository
      - name: Copy Files
        run: |
          mkdir -p output  # Assicurati che la cartella output esista
          cp -r output/* .  # Copia i file nel root del repository

      # Step 3: Commit e push delle modifiche
      - name: Commit and Push
        run: |
          git config --local user.email "your-email@example.com"  # Configura email
          git config --local user.name "Your GitHub Username"     # Configura nome
          git add .                                               # Aggiungi file
          git commit -m "Aggiornamento automatico dei file"       # Commit
          git push                                                # Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa il token integrato
